export const OrdersActionTypes = {
  SAVE_ORDER_START: 'SAVE_ORDER_START',
  SAVE_ORDER_SUCCESS: 'SAVE_ORDER_SUCCESS',
  SAVE_ORDER_FAILURE: 'SAVE_ORDER_FAILURE',
  FETCH_ORDERS_START: 'FETCH_ORDERS_START',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',
  SET_CURRENT_ORDER: 'SET_CURRENT_ORDER',
};
